### ISSUE TITLE
Async story.

### ISSUE THREAD

**Issue by krircc** [danclive/mongo-rust-driver#1]
Do you have a plan to add async, if ture , when?

**Comment by danclive** [comment]
If the rust standard library provides relevant support, I will make an asynchronous version.

**Comment by krircc** [comment]
@mitum future-await Merged in future-rs, It’s better to write library with async now.

**Comment by danclive** [comment]
But, future-await and tokio is still in the discovery phase, and it's early, and I need a stable driver right now.

**Comment by krircc** [comment]
@mitum 这个库COOL, 相对于3.6版本实现的特性覆盖率有多少,和[官方库](https://github.com/mongodb-labs/mongo-rust-driver-prototype)比较, 我想使用这个库取代官方库

**Comment by danclive** [comment]
3.6 版本主要增加了2个功能，charge stream 和 session，目前charge stream我已经实现了，session还没完成。另外，目前这个库还不支持ssl/tls，bulk write也还没做。目前这个库就我自己在用，所以，就先把我要用到的功能给实现了。

**Comment by krircc** [comment]
@mitum 不错, 快加上ssl/tls, 大家用起来 :+1:
